### ISSUE TITLE
how to run on local desktop ?

### ISSUE THREAD

**Issue by Song-xx** [emartinezs44/SparkGCN#3]
I am new to spark and GCN,I want to run the project on my desktop, is it possible? thanks a lot

**Comment by emartinezs44** [comment]
The easiest way to test the cora example is using sbt: https://www.scala-sbt.org/download.html. It handles all the dependencies. So firsst install sbt. Once it is installed clone the repo and execute sbt inside your project directory. You will see how sbt is extracting the Spark and Bigdl dependencies, it will take some minutes the first time. You can run the program either inside sbt typing: run 1 200 cora.content cora.cites or directly from the shell: sbt run 1 200 cora.content cora.cites.

Other option is to download spark and executing the run.sh script changing the SPARK_HOME

**Comment by Song-xx** [comment]
I run "sbt run 1 200 cora.content cora.cites.", it print information below,(a part of whole screen)

22-07-22 10:09:13 [run-main-0] INFO Engine$:446 - Find existing spark context. Checking the spark conf... args length: 0 
[error] (run-main-0) java.lang.IllegalArgumentException: requirement failed: Include propagation mode. 
[error] 0: to NOT apply GCN [error] 1: to APPLY GNCAnd the number of epochs 
[error] 2: dataset path 
[error] 3: edges path 
[error] java.lang.IllegalArgumentException: requirement failed: Include propagation mode. 
[error] 0: to NOT apply GCN 
[error] 1: to APPLY GNCAnd the number of epochs 
[error] 2: dataset path [error] 3: edges path 
[error] at scala.Predef$.require(Predef.scala:224) 
[error] at ems.gcn.CoraExample$.main(CoraExample.scala:54) 
[error] at ems.gcn.CoraExample.main(CoraExample.scala) 
[error] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
[error] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
[error] at java.lang.reflect.Method.invoke(Method.java:498) 
 [error] stack trace is suppressed; run last Compile / bgRun for the full output [error] Nonzero exit code: 1 [error] (Compile / run) Nonzero exit code: 1 [error] Total time: 7 s, completed 2022-7-22 10:09:13

**Comment by Song-xx** [comment]
oh,great. I run "sbt" to get into the sbt shell,then run 
"run 1 2 src/main/resources/data/cora.content src/main/resources/data/cora.cites",
and it works. thanks a loooot...
